export const authConstants = {
    LOGIN_REQUEST : 'LOGIN_REQUEST',
    LOGIN_FAILURE : 'LOGIN_FAILURE',
    LOGIN_SUCCESS : 'LOGIN_SUCCESS',
    LOGOUT_REQUEST : 'LOGOUT_REQUEST',
    LOGOUT_SUCCESS : 'LOGOUT_SUCCESS',
    LOGOUT_FAILURE : 'LOGOUT_FAILURE'
}


export const userConstants = {
    USER_REGISTER_REQUEST : 'USER_REGISTER_REQUEST',
    USER_REGISTER_SUCCESS : 'USER_REGISTER_SUCCESS',
    USER_REGISTER_FAILURE : 'USER_REGISTER_FAILURE',
}

export const categoryConstants = {
   GET_ALL_CATEGORIES_REQUEST : 'GET_ALL_CATEGORIES_REQUEST',
   GET_ALL_CATEGORIES_SUCCESS : 'GET_ALL_CATEGORIES_SUCCESS',
   GET_ALL_CATEGORIES_FAILURE : 'GET_ALL_CATEGORIES_FAILURE',
   ADD_NEW_CATEGORY_REQUEST : 'ADD_NEW_CATEGORY_REQUEST',
   ADD_NEW_CATEGORY_SUCCESS : 'ADD_NEW_CATEGORY_SUCCESS',
   ADD_NEW_CATEGORY_FAILURE : 'ADD_NEW_CATEGORY_FAILURE',
   UPDATE_CATEGORIES_REQUEST : 'UPDATE_CATEGORIES_REQUEST',
   UPDATE_CATEGORIES_SUCCESS : 'UPDATE_CATEGORIES_SUCCESS',
   UPDATE_CATEGORIES_FAILURE : 'UPDATE_CATEGORIES_FAILURE',
   DELETE_CATEGORIES_REQUEST : 'DELETE_CATEGORIES_REQUEST',
   DELETE_CATEGORIES_SUCCESS : 'DELETE_CATEGORIES_SUCCESS',
   DELETE_CATEGORIES_FAILURE : 'DELETE_CATEGORIES_FAILURE'
}

export const productConstants = {
    GET_ALL_PRODUCTS_REQUEST : 'GET_ALL_PRODUCTS_REQUEST',
    GET_ALL_PRODUCTS_SUCCESS : 'GET_ALL_PRODUCTS_SUCCESS',
    GET_ALL_PRODUCTS_FAILURE : 'GET_ALL_PRODUCTS_FAILURE',
    ADD_PRODUCT_REQUEST : 'ADD_PRODUCT_REQUEST',
    ADD_PRODUCT_SUCCESS : 'ADD_PRODUCT_SUCCESS',
    ADD_PRODUCT_FAILURE : 'ADD_PRODUCT_FAILURE',
    DELETE_PRODUCT_BY_ID_REQUEST : "DELETE_PRODUCT_BY_ID_REQUEST",
    DELETE_PRODUCT_BY_ID_SUCCESS : "DELETE_PRODUCT_BY_ID_SUCCESS",
    DELETE_PRODUCT_BY_ID_FAILURE : "DELETE_PRODUCT_BY_ID_FAILURE"
}

export const initialDataConstants = {
    GET_ALL_INITIAL_DATA_REQUEST : 'GET_ALL_INITIAL_DATA_REQUEST',
    GET_ALL_INITIAL_DATA_SUCCESS : 'GET_ALL_INITIAL_DATA_SUCCESS',
    GET_ALL_INITIAL_DATA_FAILURE : 'GET_ALL_INITIAL_DATA_FAILURE'
}

export const websiteUsersConstants = {
    GET_ALL_WEBSITE_USERS_REQUEST : ' GET_ALL_WEBSITE_USERS_REQUEST',
    GET_ALL_WEBSITE_USERS_SUCCESS : ' GET_ALL_WEBSITE_USERS_SUCCESS',
    GET_ALL_WEBSITE_USERS_FAILURE : ' GET_ALL_WEBSITE_USERS_FAILURE',
}

export const adminUsersConstants = {
    GET_ALL_ADMIN_USERS_SUCCESS : ' GET_ALL_ADMIN_USERS_SUCCESS'
}

export const pageConstants = {
    CREATE_PAGE_REQUEST : 'CREATE_PAGE_REQUEST',
    CREATE_PAGE_SUCCESS : 'CREATE_PAGE_SUCCESS',
    CREATE_PAGE_FAILURE : 'CREATE_PAGE_FAILURE',

    GET_ALL_PAGES_REQUEST : 'GET_ALL_PAGES_REQUEST',
    GET_ALL_PAGES_SUCCESS : 'GET_ALL_PAGES_SUCCESS',
    GET_ALL_PAGES_FAILURE : 'GET_ALL_PAGES_FAILURE'
}

export const orderConstants = {
    GET_CUSTOMER_ORDER_REQUEST: "GET_CUSTOMER_ORDER_REQUEST",
    GET_CUSTOMER_ORDER_SUCCESS: "GET_CUSTOMER_ORDER_SUCCESS",
    GET_CUSTOMER_ORDER_FAILURE: "GET_CUSTOMER_ORDER_FAILURE",
    UPDATE_CUSTOMER_ORDER_REQUEST : "UPDATE_CUSTOMER_ORDER_REQUEST",
    UPDATE_CUSTOMER_ORDER_SUCCESS : "UPDATE_CUSTOMER_ORDER_SUCCESS",
    UPDATE_CUSTOMER_ORDER_FAILURE : "UPDATE_CUSTOMER_ORDER_FAILURE"
}

export const homePageConstants = {
    CREATE_HOME_PAGE_REQUEST : "CREATE_HOME_PAGE_REQUEST",
    CREATE_HOME_PAGE_SUCCESS : "CREATE_HOME_PAGE_SUCCESS",
    CREATE_HOME_PAGE_FAILURE : "CREATE_HOME_PAGE_FAILURE",
    GET_HOMEPAGE_REQUEST : "GET_HOMEPAGE_REQUEST",
    GET_HOMEPAGE_SUCCESS : "GET_HOMEPAGE_SUCCESS",
    GET_HOMEPAGE_FAILURE : "GET_HOMEPAGE_FAILURE"
}

